default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: alexandria_development

test:
  <<: *default
  database: alexandria_test

production:
  <<: *default
  database: alexandria_production
  username: postgres
